apiVersion: v1
kind: Pod
metadata:
  name: dbscriptmanager
spec:
  containers:
    - name: dbscriptmanager
      image: 819563108174.dkr.ecr.us-east-2.amazonaws.com/hdfcb-ef-mum:dbdeploymentmanager-0.0.1
      imagePullPolicy: Always
      ports:
        - containerPort: 80
  restartPolicy: Never
